apiVersion: v2
name: hello-world-sb
version: 0.1.1
description: A Helm chart for deploying hello-world Spring Boot microservice.
type: application
home: https://github.com/shellclear/helm-umbrella
appVersion: 1.0.0
