apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-config
  labels:
{{- include "java-hello-world.labels" . | indent 4 }}
{{- include "java-hello-world.commonLabels" . | indent 4 }}
{{- if .Values.labels }}
{{ toYaml .Values.labels | indent 4 }}
{{- end }}
{{- if .Values.annotations }}
  annotations:
{{ toYaml .Values.annotations | indent 4 }}
{{- end }}
data:
  readme: |-
{{ .Values.config.readme | indent 4 }}
