apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    {{- include "hello-world-sb.labels" . | nindent 4 }}
    {{- include "hello-world-sb.commonLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.springboot.replicaCount }}
  selector:
    matchLabels:
      app_name: {{ .Values.name }}
      deploymentconfig: {{ .Values.name }}
  template:
    metadata:
      labels:
        {{- include "hello-world-sb.labels" . | nindent 8 }}
        {{- include "hello-world-sb.commonLabels" . | nindent 8 }}        
        deploymentconfig: {{ .Values.name }}
    spec:
      containers:
      - name: {{ .Values.name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.version }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
          {{- range .Values.env }}
          - name: {{ .name }}
            value: {{ .value }}
          {{- end }}
